### PR TITLE
Run on self-hosted runner

### PR DESCRIPTION
**Pull request by pmikolajczyk41**
Follow https://github.com/Cardinal-Cryptography/aleph-node/pull/903

### CODE REVIEW

**Comment by fbielejec** [comment]
> 1. Follow [A0-1803: Switch to self-hosted runners  #903](https://github.com/Cardinal-Cryptography/aleph-node/pull/903)
> 2. Remove unused workflow files

There are quite a few workflow files removed - can you explain pls? They are not used on **this** branch but surely  they are used on the master, where it eventually be merged?

**Comment by pmikolajczyk41** [comment]
@fbielejec I've removed them just to clear the directory from unmaintained files - I wanted to keep only the files that are actually used and we care about; once we merge into master, they will be restored

**Comment by fbielejec** [comment]
> @fbielejec I've removed them just to clear the directory from unmaintained files - I wanted to keep only the files that are actually used and we care about; once we merge into master, they will be restored

I don't understand this argument - what do you mean unmaintained? All these files are under version control and have changes ~3 days from now (https://github.com/Cardinal-Cryptography/aleph-node/tree/main/.github/workflows). You should be merging the changes, not removing these files

**Comment by pmikolajczyk41** [comment]
they are not maintained nor used on `snarkeling` branch

**Comment by fbielejec** [comment]
> they are not maintained nor used on `snarkeling` branch; but it's not a big deal, I can restore them - they'll be just rubbish files until mergin into main

that's not how version-control is supposed to work - if you remove them there will be merge conflicts. Now you're relying on a weakest link, which is human memory - what if it's not you merging these changes? how will she know what is the right way to resolve?

**Comment by pmikolajczyk41** [comment]
will be done as part of #958

**Comment by pmikolajczyk41** [comment]
will be done as part of #958

**Review by Marcin-Radecki — APPROVED** [review]

**Pull request merged**
