### PR TITLE
AZ-569: Replace the afa logging target

### PR DESCRIPTION
**Pull request by artemis-cc**
Create new logging targets `aleph-data-store`, `aleph-finality`, and
`aleph-metrics`. Remove logging target `afa`.

Replace uses of logging targets:
* (18) `afa` -> `aleph-party`
* (11) `afa` -> `aleph-data-store`
* (10) `afa` -> `aleph-justification`
* (8) `afa` -> `aleph-finality`
* (2) `afa` -> `aleph-metrics`

### CODE REVIEW

**Review by Yithis — APPROVED** [review]
LGTM

**Review by h4nsu — APPROVED** [review]

**Comment by timorl** [comment]
At least `run_nodes.sh` and `docker/docker_entrypoint.sh` still refer to "afa" and should likely be updated with something related to the new targets.

**Comment by artemis-cc** [comment]
Ah, I see, those slipped through my `grep` becaues I was using `-w`. Thanks for catching that!

**Comment by artemis-cc** [comment]
I did a `grep` without `-w` and squinted carefully at the output and it looks like the instances in `run_nodes.sh` and `docker/docker_entrypoint.sh` are the only remaining ones.

**Review by h4nsu — APPROVED** [review]

**Review by Yithis — APPROVED** [review]

**Pull request merged**
