### PR TITLE
Fix node's identity crisis

### PR DESCRIPTION
**Pull request by h4nsu**
The goal is to change the node's name displayed in the wallet:
image

to Aleph Node

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Infrastructure updated accordingly
- [x] I have made corresponding changes to the documentation
- [x] New documentation created
- [x] Bump `spec_version` and `transaction_version` if relevant
- [x] Bump `aleph-client` version if relevant

### CODE REVIEW

**Review by pmikolajczyk41 — APPROVED** [review]

**Review by timorl — APPROVED** [review]

**Review by pmikolajczyk41 — COMMENTED** [review]
actually, `support_url` could also be more appropriate :P

**Comment by timorl** [comment]
Good point, but I'm not sure we have one. :/

**Review by deuszx — APPROVED** [review]

**Comment by h4nsu** [comment]
I thought about adjusting `support_url` too, but I haven't found if and where it is displayed in the wallet... So not sure what we should put there...

**Review by kostekIV — APPROVED** [review]

**Comment by pmikolajczyk41** [comment]
it is surely displayed in logs, so external validators will see it in case of failure

I would paste maybe Discord channel link or something like this

**Comment by timorl** [comment]
I quickly asked Antek, and he suggested pointing to docs.alephzero.org .

**Pull request merged**
