### PR TITLE
add keys

### PR DESCRIPTION
**Pull request by fbielejec**
# Description

- add v-keys
- allow for v-key overwriting and deleting by a root account in runtime storage
- fixes the public inputs representation in the finite field (to match relation as written in HouseSnark)

### CODE REVIEW

**Comment by deuszx** [comment]
Can you merge with `snarkeling` first?

**Comment by deuszx** [comment]
> > Can you merge with `snarkeling` first?
> 
> Not sure I understand?

This PR has changes in the diff that were already merged.

**Comment by fbielejec** [comment]
> > > Can you merge with `snarkeling` first?
> > 
> > 
> > Not sure I understand?
> 
> This PR has changes in the diff that were already merged.

no. previous PR was merged into this branch

**Comment by fbielejec** [comment]
Since it wasn't merged I will take the opportunity and work on the runtime bits to address the problems we had with changing the verifying keys during the hackathon - I will re-open once doen

**Review by pmikolajczyk41 — APPROVED** [review]

**Pull request merged**
